"""Integration test: Path A guided intake feeds the section flow.

Mirrors ``test_root_skills_generation.py`` but starts from a guided
intake rather than uploaded documents. Exercises the deterministic
data path:

  1. The root loads ``sow-guided-intake`` (AutoScopedSkillToolset adds
     it to ``state[STATE_SKILL_CURRENT]``).
  2. The skill finishes; the toolset prunes it when the root loads the
     first section skill.
  3. The root persists administrative metadata derived from the
     ``<intake_summary>`` via ``save_sow_metadata``.
  4. The root walks the five section skills, persisting each bundle.
  5. ``assemble_sow_payload(stage="full")`` succeeds from the envelope
     with no Extraction Manifest in state.

Notes:

  - This is the deterministic-data-path style of test, NOT an LLM
    integration. The intake summary is built in-test, not generated by
    a model.
  - The Path B regression is already covered by
    ``test_root_skills_generation.py``; this file does not duplicate it.
"""
from __future__ import annotations

from types import SimpleNamespace
from typing import Any

import pytest
from google.genai import types

from app.agent import _skill_toolset
from app.shared.auto_scoped_skill_toolset import (
    STATE_SKILL_CURRENT,
    STATE_SKILL_INACTIVE,
    STATE_SKILL_PRUNE_TOTALS,
    ScopedLoadSkillTool,
)
from app.sub_agents.schemas import (
    SOW_BUNDLE_STATE_KEYS,
    SOW_METADATA_STATE_KEY,
)
from app.tools.sow.assemble_payload import assemble_sow_payload
from app.tools.sow.save_section_bundle import (
    save_architecture_bundle,
    save_delivery_plan_bundle,
    save_narrative_bundle,
    save_requirements_bundle,
    save_scope_boundaries_bundle,
)
from app.tools.sow.save_sow_metadata import save_sow_metadata


# ---------------------------------------------------------------------------
# Synthetic LLM request and context plumbing — copied (lightly) from
# test_root_skills_generation.py so this file remains self-contained.
# ---------------------------------------------------------------------------


def _load_skill_pair(skill_name: str) -> list[types.Content]:
    return [
        types.Content(
            role='model',
            parts=[
                types.Part(
                    function_call=types.FunctionCall(
                        name='load_skill', args={'skill_name': skill_name}
                    )
                )
            ],
        ),
        types.Content(
            role='user',
            parts=[
                types.Part(
                    function_response=types.FunctionResponse(
                        name='load_skill',
                        response={
                            'skill_name': skill_name,
                            'instructions': f'# SKILL.md {skill_name}\n' + 'x' * 500,
                        },
                    )
                )
            ],
        ),
    ]


class _FakeLlmRequest:
    def __init__(self, contents: list[types.Content]):
        self.contents = list(contents)
        self.appended_instructions: list[Any] = []

    def append_instructions(self, instructions: Any) -> None:
        self.appended_instructions.append(instructions)


def _ctx(state: dict[str, Any]) -> SimpleNamespace:
    return SimpleNamespace(
        state=state,
        agent_name='pre_sales_assistant',
        invocation_id='test-invocation-path-a',
    )


# ---------------------------------------------------------------------------
# Sample intake summary + metadata extracted from it
# ---------------------------------------------------------------------------


SAMPLE_INTAKE_SUMMARY = """<intake_summary>
Customer:
- Acme Corp

Partner:
- GFT Technologies

Project:
- Data Analytics Platform

Funding:
- DAF

Problem / Goal:
- Acme needs a centralized analytics platform on GCP to consolidate sales reporting.

Solution Direction:
- A BigQuery-centered data warehouse fed by Cloud Run ingestion services.

Engagement Shape:
- greenfield

Main Scope:
- Ingest data from SAP and Salesforce
- Build a BigQuery warehouse with curated marts
- Expose dashboards via Looker Studio

Out of Scope:
- (inferred)

Integrations / Systems:
- SAP — source, REST, read
- Salesforce — source, batch, read

Team:
- Partner side: (inferred)
- Customer side: Project sponsor, two SMEs

Timeline:
- 10 weeks starting 2026-06-01

NFR / Quality Targets:
- Latency: dashboards refresh under 5 minutes
- Security: TLS 1.3 in transit, AES-256 at rest

Assumptions / Constraints:
- Customer provides VPN access on day 1
- (inferred) Industry-standard LGPD compliance applies

Open Items:
- Out-of-scope items: (inferred)
- Partner team composition: (inferred)
- Industry compliance frameworks: (inferred)
</intake_summary>
"""


def _metadata_from_summary() -> dict[str, str]:
    """The administrative fields the root would extract from the summary
    above. The contract is documented in
    ``app/skills/sow-guided-intake/references/intake-summary-format.md``."""
    return {
        'partner_name': 'GFT Technologies',
        'customer_name': 'Acme Corp',
        'partner_short_name': 'GFT',
        'customer_short_name': 'Acme',
        'project_title': 'Data Analytics Platform',
        'date': '2026-05-27',
        'author': 'Root Agent',
        'funding_type': 'Google DAF',
        'funding_type_short': 'DAF',
        'project_start_date': '2026-06-01',
        'project_end_date': '2026-08-10',
        'engagement_type': 'project',
        'organization_term': 'phases',
    }


# ---------------------------------------------------------------------------
# Minimal but schema-valid bundles — same builders as
# test_root_skills_generation.py so the assembly contract is exercised.
# ---------------------------------------------------------------------------


def _requirements() -> dict[str, Any]:
    return {
        'functional_requirements': [
            {'number': 'FR-01', 'description': 'Ingest data from SAP.'},
        ],
        'non_functional_requirements': [
            {'number': 'NFR-01', 'description': 'TLS 1.3 in transit.'},
        ],
    }


def _delivery_plan() -> dict[str, Any]:
    return {
        'activity_phases': [
            {'name': 'Phase 1', 'description': 'Discovery.', 'tasks': ['Kickoff']},
        ],
        'deliverables': [
            {'activity': 'Phase 1', 'name': 'Spec', 'description': 'Design spec.', 'format': 'Document'},
        ],
        'timeline': [{'activity': 'Phase 1', 'timeframe': 'W1-2', 'outcomes': 'Spec done.'}],
        'partner_roles': [{'role': 'PM', 'responsibilities': 'Owns plan.'}],
        'customer_roles': [{'role': 'Sponsor', 'responsibilities': 'Approves.'}],
        'success_criteria': ['Plan accepted.'],
        'objectives': ['Modernize.'],
    }


def _scope_boundaries() -> dict[str, Any]:
    return {
        'assumptions': ['Customer provides VPN access.'],
        'out_of_scope': ['Hardware procurement.'],
        'risks': [{'description': 'SAP rate limits.', 'mitigation': 'Backoff.'}],
        'handover_disclaimers': ['KT in week 10.'],
        'change_request_policy_text': 'Written approval required.',
    }


def _architecture() -> dict[str, Any]:
    return {
        'architecture_description': 'Layered serverless architecture on GCP.',
        'architecture_components': [{'name': 'Cloud Run', 'role': 'API host.'}],
        'architecture_integrations': [{'name': 'SAP', 'description': 'Source.'}],
        'technology_stack': [{'service': 'BigQuery', 'purpose': 'Warehouse.'}],
    }


def _narrative() -> dict[str, Any]:
    return {
        'executive_summary': 'Modernizes Acme data analytics on GCP.',
        'partner_overview': 'GFT is a GCP premier partner.',
        'customer_overview': 'Acme manufactures globally.',
        'customer_primary_domain': 'acme.com',
    }


_SECTIONS = [
    ('sow-requirements', save_requirements_bundle, _requirements, 'requirements'),
    ('sow-delivery-plan', save_delivery_plan_bundle, _delivery_plan, 'delivery_plan'),
    ('sow-scope-boundaries', save_scope_boundaries_bundle, _scope_boundaries, 'scope_boundaries'),
    ('sow-architecture', save_architecture_bundle, _architecture, 'architecture'),
    ('sow-narrative', save_narrative_bundle, _narrative, 'narrative'),
]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestPathAGuidedIntake:
    async def test_guided_intake_skill_is_loadable_via_root_toolset(self):
        """``load_skill('sow-guided-intake')`` is the gate to Path A.

        The toolset must register the skill so the root can call it
        without an "unknown skill" error.
        """
        state: dict[str, Any] = {}
        ctx = _ctx(state)
        load_tool = next(
            t for t in _skill_toolset._tools if isinstance(t, ScopedLoadSkillTool)
        )
        result = await load_tool.run_async(
            args={'skill_name': 'sow-guided-intake'}, tool_context=ctx
        )
        assert result is not None
        assert state[STATE_SKILL_CURRENT] == 'sow-guided-intake'

    async def test_full_path_a_protocol_drives_section_pipeline(self):
        """End-to-end deterministic walk of Path A.

        1. Activate ``sow-guided-intake``.
        2. Switch to the section skills (pruning the intake skill).
        3. Persist metadata and the five bundles.
        4. Assemble the full payload and spot-check fields.
        """
        state: dict[str, Any] = {}
        ctx = _ctx(state)
        load_tool = next(
            t for t in _skill_toolset._tools if isinstance(t, ScopedLoadSkillTool)
        )

        # Step 1 — guided intake skill enters scope.
        await load_tool.run_async(
            args={'skill_name': 'sow-guided-intake'}, tool_context=ctx
        )
        assert state[STATE_SKILL_CURRENT] == 'sow-guided-intake'

        # Inject a fake llm_request that exercises the toolset's prune
        # path on the very next skill switch (mimics what the root does
        # after the guided interview returns the <intake_summary>).
        previous_skill = 'sow-guided-intake'

        # Step 2 — metadata derived from the intake summary.
        assert SAMPLE_INTAKE_SUMMARY.startswith('<intake_summary>')
        meta_result = await save_sow_metadata(
            tool_context=ctx, **_metadata_from_summary()
        )
        assert meta_result['status'] == 'success', meta_result
        assert SOW_METADATA_STATE_KEY in state

        # Step 3 — walk the five section skills in order, with pruning.
        for skill_name, save_tool, builder, section_key in _SECTIONS:
            await load_tool.run_async(
                args={'skill_name': skill_name}, tool_context=ctx
            )
            req = _FakeLlmRequest(
                _load_skill_pair(previous_skill) + _load_skill_pair(skill_name)
            )
            await _skill_toolset.process_llm_request(
                tool_context=ctx, llm_request=req
            )
            save_result = await save_tool(bundle=builder(), tool_context=ctx)
            assert save_result['status'] == 'success', (
                f'{skill_name} bundle save failed: {save_result}'
            )
            previous_skill = skill_name

        # All bundles persisted.
        for _skill, _save, _builder, section_key in _SECTIONS:
            assert SOW_BUNDLE_STATE_KEYS[section_key] in state

        # The guided intake skill must end up in the inactive set after
        # the section walk — its content was pruned from the LLM
        # context.
        inactive = state[STATE_SKILL_INACTIVE]
        assert 'sow-guided-intake' in inactive, (
            'sow-guided-intake should have been pruned to inactive after '
            'the root advanced to the section skills.'
        )
        # And the final current skill is the last section.
        assert state[STATE_SKILL_CURRENT] == 'sow-narrative'

        # Pruning fired at every switch — 1 (intake → requirements) +
        # 4 between the section skills = 5 prune events.
        totals = state[STATE_SKILL_PRUNE_TOTALS]
        assert totals['prune_event_count'] == 5

        # No Extraction Manifest state involved — Path A is summary-only.
        assert 'extraction_manifest' not in state
        assert 'app:extraction_manifest' not in state

        # Assemble the full payload from the envelope.
        result = await assemble_sow_payload(stage='full', tool_context=ctx)
        assert result['status'] == 'success', result
        sow = result['data']['sow_data']
        assert sow['project_title'] == 'Data Analytics Platform'
        assert sow['customer_name'] == 'Acme Corp'
        assert sow['funding_type_short'] == 'DAF'
