"""Scope-boundaries section repair sub-agent.

In the root-skills variant the first-gen scope-boundaries section is
generated by the root inline (``load_skill('sow-scope-boundaries')`` →
``save_scope_boundaries_bundle``). This module ships only
``scope_boundaries_repair_agent``, invoked by the QualityLoopAgent in
repair mode to patch the bundle via ``apply_scope_boundaries_patch``
instead of regenerating it.
"""

from __future__ import annotations

from ...tools.sow.apply_section_patch import apply_scope_boundaries_patch
from ..schemas import SOW_BUNDLE_STATE_KEYS
from .._section_agent import build_section_repair_agent

SCOPE_BOUNDARIES_OUTPUT_KEY: str = SOW_BUNDLE_STATE_KEYS['scope_boundaries']


scope_boundaries_repair_agent = build_section_repair_agent(
    name='scope_boundaries_repair_agent',
    description=(
        'Repair specialist for the scope-boundaries section. Applies a '
        'batch of patch ops to the in-state ScopeBoundariesBundle via '
        '`apply_scope_boundaries_patch` instead of regenerating the bundle. '
        'Invoked exclusively by the QualityLoopAgent.'
    ),
    section_name='scope_boundaries',
    skill_name='sow-scope-boundaries',
    bundle_key=SCOPE_BOUNDARIES_OUTPUT_KEY,
    patch_tool=apply_scope_boundaries_patch,
    state_inputs=(
        ('prior_requirements', SOW_BUNDLE_STATE_KEYS['requirements']),
        ('prior_delivery_plan', SOW_BUNDLE_STATE_KEYS['delivery_plan']),
    ),
)
