"""Requirements section repair sub-agent (FR + NFR).

In the root-skills variant the first-gen requirements section is
generated by the root inline (``load_skill('sow-requirements')`` →
``save_requirements_bundle``); there is no longer a
``requirements_agent``. This module ships only
``requirements_repair_agent``, invoked by the QualityLoopAgent in
repair mode to patch the bundle via ``apply_requirements_patch``
instead of regenerating it.
"""

from __future__ import annotations

from ...tools.sow.apply_section_patch import apply_requirements_patch
from ..schemas import SOW_BUNDLE_STATE_KEYS
from .._section_agent import build_section_repair_agent

REQUIREMENTS_OUTPUT_KEY: str = SOW_BUNDLE_STATE_KEYS['requirements']


requirements_repair_agent = build_section_repair_agent(
    name='requirements_repair_agent',
    description=(
        'Repair specialist for the requirements section. Applies a batch '
        'of patch ops to the in-state RequirementsBundle via '
        '`apply_requirements_patch` instead of regenerating the bundle. '
        'Invoked exclusively by the QualityLoopAgent.'
    ),
    section_name='requirements',
    skill_name='sow-requirements',
    bundle_key=REQUIREMENTS_OUTPUT_KEY,
    patch_tool=apply_requirements_patch,
)
