"""Delivery-plan section repair sub-agent.

In the root-skills variant the first-gen delivery-plan section is
generated by the root inline (``load_skill('sow-delivery-plan')`` →
``save_delivery_plan_bundle``). This module ships only
:data:`delivery_plan_repair_agent` (single Agent, tool-based), invoked
by the QualityLoopAgent in repair mode. It uses
:func:`app.tools.sow.apply_section_patch.apply_delivery_plan_patch` to
mutate the bundle transactionally instead of regenerating it.
"""

from __future__ import annotations

from ...tools.sow.apply_section_patch import apply_delivery_plan_patch
from ..schemas import SOW_BUNDLE_STATE_KEYS
from .._section_agent import build_section_repair_agent

DELIVERY_PLAN_OUTPUT_KEY: str = SOW_BUNDLE_STATE_KEYS['delivery_plan']


delivery_plan_repair_agent = build_section_repair_agent(
    name='delivery_plan_repair_agent',
    description=(
        'Repair specialist for the delivery-plan section. Reads '
        '`<repair_findings>` from state and applies a batch of patch ops '
        'to the in-state DeliveryPlanBundle via `apply_delivery_plan_patch`, '
        'instead of regenerating the bundle. Invoked exclusively by the '
        'QualityLoopAgent; never wired into the root.'
    ),
    section_name='delivery_plan',
    skill_name='sow-delivery-plan',
    bundle_key=DELIVERY_PLAN_OUTPUT_KEY,
    patch_tool=apply_delivery_plan_patch,
    state_inputs=(
        ('prior_requirements', SOW_BUNDLE_STATE_KEYS['requirements']),
    ),
)
