"""Architecture section sub-agent — Phase 2 Step D.

Receives :func:`generate_architecture_diagram` as an extra worker tool
so the same agent that drafts ``architecture_description`` /
``architecture_components`` / ``architecture_integrations`` /
``technology_stack`` also produces the diagram PNG artifact in the
same turn (Contract 3 of the legacy ``sow-architecture`` skill: the
three-way invariant description↔table↔diagram).

The bundle Pydantic schema does NOT carry the diagram bytes — the
diagram is saved as a session artifact and the document generator
attaches it during ``generate_sow_document``. This agent's
:class:`ArchitectureBundle` covers only the structured text fields.
"""

from __future__ import annotations

from ...tools.sow.apply_section_patch import apply_architecture_patch
from ...tools.sow.generate_architecture_diagram import \
    generate_architecture_diagram
from ..schemas import ArchitectureBundle, SOW_BUNDLE_STATE_KEYS
from .._section_agent import build_section_agent, build_section_repair_agent

ARCHITECTURE_OUTPUT_KEY: str = SOW_BUNDLE_STATE_KEYS['architecture']

_OUTPUT_EXAMPLE = """\
{"architecture_description": "End users send HTTPS requests to ...",
 "architecture_components": [{"name": "Cloud Run", "role": "Hosts the API."}],
 "architecture_integrations": [{"name": "SAP ERP",
                                "description": "Source system via REST."}],
 "technology_stack": [{"service": "Cloud Run",
                       "purpose": "Serverless API layer."}]}"""


architecture_agent = build_section_agent(
    name='architecture_agent',
    description=(
        'Generates the architecture cluster: description, components, '
        'integrations, technology stack, and the diagram PNG artifact '
        '(via generate_architecture_diagram). Runs the three-way '
        'invariant description↔table↔diagram + component checklist '
        'before returning. Writes an ArchitectureBundle to '
        f'`state[{ARCHITECTURE_OUTPUT_KEY!r}]`.'
    ),
    skill_name='sow-architecture',
    output_schema=ArchitectureBundle,
    output_key=ARCHITECTURE_OUTPUT_KEY,
    output_example=_OUTPUT_EXAMPLE,
    extra_tools=[generate_architecture_diagram],
    state_inputs=(
        ('extraction_manifest', SOW_BUNDLE_STATE_KEYS['manifest']),
        ('prior_requirements', SOW_BUNDLE_STATE_KEYS['requirements']),
        ('prior_delivery_plan', SOW_BUNDLE_STATE_KEYS['delivery_plan']),
        ('prior_scope_boundaries', SOW_BUNDLE_STATE_KEYS['scope_boundaries']),
    ),
)


# ``generate_architecture_diagram`` is deliberately NOT passed to the
# repair agent. The diagram artifact is regenerated by the first-gen
# agent only — in repair mode, the bundle's text fields are mutated
# via the patch tool. If a finding flags a diagram defect, the agent
# corrects the matching bundle field (which the document generator
# reads when re-rendering the diagram); commissioning a new PNG mid-
# repair would re-introduce the three-way drift the first-gen
# invariant exists to prevent.
architecture_repair_agent = build_section_repair_agent(
    name='architecture_repair_agent',
    description=(
        'Repair-mode counterpart of `architecture_agent`. Applies a batch '
        'of patch ops to the in-state ArchitectureBundle via '
        '`apply_architecture_patch` instead of regenerating the bundle. '
        'Does NOT regenerate the diagram artifact — the PNG is re-rendered '
        'by the document generator from the patched bundle. Invoked '
        'exclusively by the QualityLoopAgent.'
    ),
    section_name='architecture',
    skill_name='sow-architecture',
    bundle_key=ARCHITECTURE_OUTPUT_KEY,
    patch_tool=apply_architecture_patch,
    state_inputs=(
        ('extraction_manifest', SOW_BUNDLE_STATE_KEYS['manifest']),
        ('prior_requirements', SOW_BUNDLE_STATE_KEYS['requirements']),
        ('prior_delivery_plan', SOW_BUNDLE_STATE_KEYS['delivery_plan']),
        ('prior_scope_boundaries', SOW_BUNDLE_STATE_KEYS['scope_boundaries']),
    ),
)
