"""Architecture section repair sub-agent.

In the root-skills variant the first-gen architecture section is
generated by the root inline (``load_skill('sow-architecture')`` →
``save_architecture_bundle``), and the diagram PNG is rendered by the
root's ``generate_architecture_diagram`` tool. This module ships only
``architecture_repair_agent``, invoked by the QualityLoopAgent in
repair mode to patch the bundle via ``apply_architecture_patch``.

The repair agent does NOT regenerate the diagram artifact — the PNG is
re-rendered by the document generator from the patched bundle. If a
finding flags a diagram defect, the agent corrects the matching bundle
field; commissioning a new PNG mid-repair would re-introduce the
three-way description↔table↔diagram drift the first-gen invariant
exists to prevent.
"""

from __future__ import annotations

from ...tools.sow.apply_section_patch import apply_architecture_patch
from ..schemas import SOW_BUNDLE_STATE_KEYS
from .._section_agent import build_section_repair_agent

ARCHITECTURE_OUTPUT_KEY: str = SOW_BUNDLE_STATE_KEYS['architecture']


architecture_repair_agent = build_section_repair_agent(
    name='architecture_repair_agent',
    description=(
        'Repair specialist for the architecture section. Applies a batch '
        'of patch ops to the in-state ArchitectureBundle via '
        '`apply_architecture_patch` instead of regenerating the bundle. '
        'Does NOT regenerate the diagram artifact — the PNG is re-rendered '
        'by the document generator from the patched bundle. Invoked '
        'exclusively by the QualityLoopAgent.'
    ),
    section_name='architecture',
    skill_name='sow-architecture',
    bundle_key=ARCHITECTURE_OUTPUT_KEY,
    patch_tool=apply_architecture_patch,
    state_inputs=(
        ('prior_requirements', SOW_BUNDLE_STATE_KEYS['requirements']),
        ('prior_delivery_plan', SOW_BUNDLE_STATE_KEYS['delivery_plan']),
        ('prior_scope_boundaries', SOW_BUNDLE_STATE_KEYS['scope_boundaries']),
    ),
)
